Fix CI dockerfile

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,19 +8,19 @@ jobs:
   # Ref: https://github.com/rust-lang/crater/blob/9ab6f9697c901c4a44025cf0a39b73ad5b37d198/.github/workflows/bors.yml#L125-L149
   #
   # ALL THE SUBSEQUENT JOBS NEED THEIR `name` ADDED TO THE `needs` SECTION OF THIS JOB!
+  # ci-result:
+  #   name: ci result
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - ci-rasters
+  #   steps:
+  #     - name: Mark the job as a success
+  #       if: success()
+  #       run: exit 0
+  #     - name: Mark the job as a failure
+  #       if: "!success()"
+  #       run: exit 1
   ci-result:
-    name: ci result
-    runs-on: ubuntu-latest
-    needs:
-      - ci-rasters
-    steps:
-      - name: Mark the job as a success
-        if: success()
-        run: exit 0
-      - name: Mark the job as a failure
-        if: "!success()"
-        run: exit 1
-  ci-rasters:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -28,11 +28,14 @@ jobs:
           - 1.57
         gdal:
           - 3.2.2
+    name: Test on gdal ${{ matrix.gdal }}, rust ${{ matrix.rust }}
     container:
       image: rmanoka/georust-ci:gdal-${{ matrix.gdal }}-rust-${{ matrix.rust }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      - name: Gdal version
-        run: gdalinfo --version
-      - run: cargo test --all-features
+      - name: Tool versions
+        run: gdalinfo --version && rustc --version
+      - run: cargo test --workspace --all-features
+      - name: raster-tools
+        run: cd raster-tools && python3 -m tests
